spring:
  datasource:
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${CREATE, VALIDATE}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
          kakao:
            clientId: ${KAKAO_REST_API_ID}
            clientSecret: ${KAKAO_SECRET_KEY}
            clientAuthenticationMethod: client_secret_post
            redirectUri: http://localhost:8080/login/oauth2/kakao
            authorizationGrantType: authorization_code
            clientName: kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
#http://localhost:8080/logout/oauth2/kakao

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    encoding:
      force-response: true

mail:
  address:
    admin: ljg980708@gmail.com

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420